"""update user table

Revision ID: 17e81c6917cf
Revises: 3ce480933278
Create Date: 2023-02-15 14:55:55.379180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e81c6917cf'
down_revision = '3ce480933278'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
