"""add user_id into item model

Revision ID: c6b3fd506bee
Revises: 5540742d1986
Create Date: 2023-02-28 18:21:43.281400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b3fd506bee'
down_revision = '5540742d1986'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'user_id')
    # ### end Alembic commands ###
