"""add marked to item

Revision ID: ec4df3fd7790
Revises: c6b3fd506bee
Create Date: 2023-03-01 14:05:19.306224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4df3fd7790'
down_revision = 'c6b3fd506bee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('marked', sa.BOOLEAN(), nullable=False))
    op.alter_column('item', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('item', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('item_location_key', 'item', type_='unique')
    op.create_unique_constraint(None, 'item', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    op.create_unique_constraint('item_location_key', 'item', ['location'])
    op.alter_column('item', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('item', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('item', 'marked')
    # ### end Alembic commands ###
