"""add metadata, collection and picture models

Revision ID: b886c51824cb
Revises: ec4df3fd7790
Create Date: 2023-03-02 14:32:09.143039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b886c51824cb'
down_revision = 'ec4df3fd7790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stratigraphy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('era', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=2000), nullable=True),
    sa.Column('epoch', sa.String(length=2000), nullable=True),
    sa.Column('age', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stratigraphy_id'), 'stratigraphy', ['id'], unique=False)
    op.create_table('taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biological_phylum', sa.String(length=50), nullable=False),
    sa.Column('biological_class', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_id'), 'taxonomy', ['id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('coordinates', sa.String(length=200), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.add_column('item', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.add_column('picture', sa.Column('created', sa.TIMESTAMP(), nullable=False))
    op.add_column('picture', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('picture', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'picture', 'item', ['item_id'], ['id'])
    op.create_foreign_key(None, 'picture', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.drop_column('picture', 'item_id')
    op.drop_column('picture', 'owner')
    op.drop_column('picture', 'created')
    op.drop_column('item', 'collection_id')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_taxonomy_id'), table_name='taxonomy')
    op.drop_table('taxonomy')
    op.drop_index(op.f('ix_stratigraphy_id'), table_name='stratigraphy')
    op.drop_table('stratigraphy')
    # ### end Alembic commands ###
