"""add constraint user-session

Revision ID: 3ce480933278
Revises: 98a63a7a3284
Create Date: 2023-02-14 18:04:29.264996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce480933278'
down_revision = '98a63a7a3284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'user_id')
    # ### end Alembic commands ###
